server:
  port: 8001
spring:
  application:
    name: sentinel-sample #应用/微服务名字
  cloud:
    nacos:
      server-addr: localhost:8848 #nacos服务器地址
      username: nacos
      password: nacos
    sentinel: #Sentinel Dashboard通信地址
      transport:
        dashboard: localhost:9100
      eager: true #取消控制台懒加载
      datasource:
        flow:
          nacos:
            server-addr: ${spring.cloud.nacos.server-addr}
            dataId: ${spring.application.name}-flow-rules
            groupId: SAMPLE_GROUP
            # 规则类型，取值见：
            # org.springframework.cloud.alibaba.sentinel.datasource.RuleType
            rule-type: flow
            username: nacos
            password: nacos
        degrade:
          nacos:
            server-addr: ${spring.cloud.nacos.server-addr}
            dataId: ${spring.application.name}-degrade-rules
            groupId: SAMPLE_GROUP
            rule-type: degrade #代表熔断
            username: nacos
            password: nacos
management:
  endpoints:
    web: #将所有可用的监控指标项对外暴露
      exposure: #可以访问 /actuator/sentinel进行查看Sentinel监控项
        include: '*'
logging:
  level:
    root: info

